### ISSUE TITLE
Email spec. should be synced to emailjs account of WG

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#12]
@phann-phearoen 

Thank you for embedding emailjs library logic into the page in advance.
I think we have to modify your logic of sending mail by arranging suitable specs to the account of WG from emailjs.

Let me follow it up soon. 
Let's try to develop extra codes via ZOOM meeting by sharing our screen :)

<img width="958" alt="Screen Shot 2021-07-22 at 1 27 19" src="https://user-images.githubusercontent.com/14138179/126525123-af2f8149-0eaf-45ef-95b5-c6eaeeb21ac7.png">

<img width="1304" alt="Screen Shot 2021-07-22 at 1 30 41" src="https://user-images.githubusercontent.com/14138179/126525332-7c5378d5-a9e5-4c9b-b880-61c270b6897c.png">

**Comment by geonsangyoo** [comment]
@phann-phearoen 

In terms of emailjs, 
you have to create a new gmail format at emailjs through WG account.

Seemingly, your code embedded into your vue file has been completed to your gmail format.
I think it is much faster to copy your format into WG account.

Can you handle it? Let me share WG account via Chatwork.
Please let me know details on the meeting today  :)

**Comment by geonsangyoo** [comment]
@phann-phearoen

The mail sent to WG's account is weird.
No any title and contents is included in mail.

Could you confirm the gmail format of emailjs?
It seems like data object you defined in emailjs cannot load the data sent from input forms on vue page.

<img width="479" alt="Screen Shot 2021-07-29 at 10 56 10" src="https://user-images.githubusercontent.com/14138179/127420724-fb4c5b3b-811f-4674-980c-09522b801fb2.png">

**Comment by phann-phearoen** [comment]
I need to be able to check the email to modify the template.

**Comment by phann-phearoen** [comment]
Can I have access to the email box?

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Sorry. I could not share it as It is representative mail address of WG.

Please let me know via Chatwork if you want to try to check your mail sent from your edited form.

I am gonna send you result.

Thank you!

**Comment by phann-phearoen** [comment]
Got it!,
I'll test it with my own mail box again, and I'll let you know when to check WG's.
Thank you!

**Comment by phann-phearoen** [comment]
<img width="476" alt="Success MailJs" src="https://user-images.githubusercontent.com/74291680/127423177-7947343d-fee8-491b-8ba0-3705d1ac0ed4.PNG">
Everything seems fine here!
I have redirected the email to WG's again already, please check the mail box, I've just sent a greeting email.

**Comment by geonsangyoo** [comment]
> <img alt="Success MailJs" width="476" src="https://user-images.githubusercontent.com/74291680/127423177-7947343d-fee8-491b-8ba0-3705d1ac0ed4.PNG">
> 
> Everything seems fine here! I have redirected the email to WG's again already, please check the mail box, I've just sent a greeting email.

@phann-phearoen 

Good! your test mail is successfully sent to WG account!
Please go ahead!!

<img width="577" alt="Screen Shot 2021-07-29 at 12 07 27" src="https://user-images.githubusercontent.com/14138179/127425390-3d10e453-c500-4994-bd32-e5614c313f46.png">

**Comment by phann-phearoen** [comment]
Feels so quirky, (^_^)
