### ISSUE TITLE
The margin adjustment needs to be performed on nav button

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#13]
@phann-phearoen 

<img width="378" alt="Screen Shot 2021-07-22 at 1 33 03" src="https://user-images.githubusercontent.com/14138179/126525967-2e3a3827-6739-4ee1-8442-eda81fb8c88f.png">

I think you need to add a margin(x-axis) attribute with the use of class etc for all buttons located next to icons that are too close together.

Please adjust each margin on x-axis between icons and menu texts by looking over desktop & mobile-device layout too.

**Comment by geonsangyoo** [comment]
@phann-phearoen 

There are two issues here.

1. Please fix the size whenever the user hover the scope of nav-menus. Currently, all range of nav-menu bar is slightly moving when one of nav-menu is hovered by user


https://user-images.githubusercontent.com/14138179/127420936-18004bb4-99c1-4752-aba7-cf58d3dc4453.mov


2. When an user entered on vue-pages/contact.vue page, the nav-menu bar is not working. I think you have to edit path of each url attached to each nav-menu

<img width="464" alt="Screen Shot 2021-07-29 at 11 06 37" src="https://user-images.githubusercontent.com/14138179/127421064-1dd6bc93-5b85-4e1e-978d-fa451a8236f4.png">

**Comment by phann-phearoen** [comment]
This problem is a little more complicated than that. 
Since this /contact route is a separated page from the /home, we can't use the nav-bar function to navigate.
My logic is: if user want to return to /home, user can press on "ママスク" logo on the top right(implemented).
Thus, if the nav-bar function here is disabled it would actually make a better sense. 
What do you think?

**Comment by geonsangyoo** [comment]
> This problem is a little more complicated than that.
> Since this /contact route is a separated page from the /home, we can't use the nav-bar function to navigate.
> My logic is: if user want to return to /home, user can press on "ママスク" logo on the top right(implemented).
> Thus, if the nav-bar function here is disabled it would actually make a better sense.
> What do you think?

@phann-phearoen 

In this case, you should use `<router-link>` innate tag of vue scope instead of `<a>` tag that is frequently used to transit among vue components.

Let me give you an example in your code.
Please refer below one.



[your code]


``` html
<a class="nav-link" href="#douga"><img src="./assets/icon01.png" class="img mx-2" alt="icon01">学べる動画一覧</a>
```



[The code using router-link tag]

``` html
<router-link to="home#douga" class="nav-link">
  <img src="./assets/icon01.png" class="img mx-2" alt="icon01"/>学べる動画一覧
</router-link>
```

I think the above code should work in your circumstance.
Please try it and update your codes!

Good Luck! :)

**Comment by phann-phearoen** [comment]
OMG, yes it works.
It works so damn well that my mind is exploded for how on earth did it work.
Who would have thought that this would let us have both the SPA & Scroll down functionality at the same time??!!
Thanks for the solution big bossie

**Comment by phann-phearoen** [comment]
By the way, did you change the color palette of the base text to this hot-pink?

![image](https://user-images.githubusercontent.com/74291680/127954874-2e2ca537-224c-450e-9c73-3a7287fbdb33.png)
![image](https://user-images.githubusercontent.com/74291680/127954968-f954f1e6-8e1d-43ac-8d4a-75e79c0a3064.png)

Or it is that I messed the styling somewhere?

**Comment by geonsangyoo** [comment]
> OMG, yes it works.
> It works so damn well that my mind is exploded for how on earth did it work.
> Who would have thought that this would let us have both the SPA & Scroll down functionality at the same time??!!
> Thanks for the solution big bossie

@phann-phearoen 

Please refer #22 issue comments.
Thanks.
