### ISSUE TITLE
The logo image under the mobile page is located underneath of header

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#20]
Under the mobile mode, the logo is currently located under the header area. 
Please adjust the location of the logo image center of header area.

<img width="515" alt="Screen Shot 2021-08-03 at 0 09 40" src="https://user-images.githubusercontent.com/14138179/127883655-6580dd4f-b7eb-4388-9bba-b73f230fd8b3.png">

**Comment by phann-phearoen** [comment]
Done
