### ISSUE TITLE
Text color turned pink

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#22]
Hey, text color in many base elements are now pink or somewhat reddish.
Was it intendedly modified or somehow a bug?

![image](https://user-images.githubusercontent.com/74291680/128130583-75c0bbd5-dac7-4cc2-a48d-47fe3875bd2a.png)
![image](https://user-images.githubusercontent.com/74291680/128130731-d8cef19d-a054-44d7-ba53-52d94e403cf0.png)

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Hi, Phann,

I will check your code & pages rendered soon!

Please give me some time! :)

Thanks!

**Comment by phann-phearoen** [comment]
Sure fine bossie

**Comment by geonsangyoo** [comment]
@phann-phearoen 

<img width="469" alt="Screen Shot 2021-08-04 at 16 46 58" src="https://user-images.githubusercontent.com/14138179/128142495-e0610e07-bd3b-48fb-bb5b-20d145cf18a2.png">

The cause for text changed into red color for all range wrapped from `text-center` class,
you added a suspected code block stated below a week ago.

[ToiAwase.vue]

``` css
.text-center{
    color: red;
    font-family: 'M PLUS Rounded 1c', sans-serif;
    font-weight: 300;
}
```

please check other pages again.

**Comment by phann-phearoen** [comment]
Jesus, how did you find out?! lol

I just remember that I was adding that class to tweak the look of some element inside the timepickers.
I abandoned it, and didn't know it effects other elements too.

That's the level of GitHub skill I want!!

Thank you so much!!

**Comment by geonsangyoo** [comment]
@phann-phearoen 

No worries buddy! :)

Plus, I found out it via element inspector of chrome browser which is not related to Github ^^

<img width="649" alt="Screen Shot 2021-08-04 at 17 09 20" src="https://user-images.githubusercontent.com/14138179/128145801-19d2721a-269e-4aaf-97e5-1697fb37d8ad.png">

**Comment by phann-phearoen** [comment]
Ahah, too shame, lol
I really should have done that.

**Comment by phann-phearoen** [comment]
Ahah, too shame, lol
I really should have done that.
