### ISSUE TITLE
[Server Deployment] Waiting for instance running

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#24]
@phann-phearoen 

Thank you for your hardworking!

It seems okay to deploy on the server.

please wait for a moment until new aws instance is created.

In the meanwhile, please refer a brief manual like below.
(Below site is written by Korean. please translate it via sub-functionality of web-browser)

```
https://daily-life-of-bsh.tistory.com/223
```

<img width="883" alt="Screen Shot 2021-08-04 at 22 39 36" src="https://user-images.githubusercontent.com/14138179/128190969-51adc4b8-0f66-427c-9ca8-20dfd2e3b30b.png">

To be specific, I will reach out to you soon. :)

**Comment by phann-phearoen** [comment]
Okey, thank you bossy!

2021年8月4日(水) 午後8:39 geonsangyoo ***@***.***>:
