### ISSUE TITLE
Change Attention Texts (予約フォーム)

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#31]
Change Attention Texts:
from:
万が一 24 時間以上経っても連絡がない場合はテキストテキストテキストテキストテキストテキスト。
to:
3日以上経過しても連絡がない場合、何らかのトラブルにより
こちらにメールが届いていない可能性がございます。
その際は、お手数をおかけしますが再度ご連絡いただけますと幸いです。

Code Location: store/yoyakuInfoModule.js

**Comment by geonsangyoo** [comment]
@phann-phearoen 
Confirmed
