### ISSUE TITLE
Mobile Mode Margin Gets Too Large

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#33]
Margin bottom under 送信 button in お問い合わせ is too large.

Code Location: components/ToiAwase.vue

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Please lessen empty space between register button and form half by current status.

<img width="580" alt="Screen Shot 2021-08-12 at 10 55 36" src="https://user-images.githubusercontent.com/14138179/129126598-8311e865-0680-4f57-8551-eb1e4804bcec.png">

**Comment by phann-phearoen** [comment]
Done

**Comment by geonsangyoo** [comment]
@phann-phearoen 
Confirmed
