### ISSUE TITLE
Date Picker Needs to be in Japanese Format 

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#37]
Date Picker needs to be in Japanese format (language).

Code Location: components/yoyaku-contact-row/ContactRow.vue

**Comment by phann-phearoen** [comment]
Hey, need some help here.
I get stuck in this issue. I can't find a way to display those calendar in Japanese.
There is a simple way in Quasar, which is using Language Pack. 

https://quasar.dev/options/quasar-language-packs

First we need to Internationalize our App.

https://quasar.dev/options/app-internationalization

Then with Language Pack, we can simply import a language and specify it, then Quasar elements will automatically display in that language.

The problem is that those 2 functionalities only support project created using Quasar CLI, and our project is using Vue CLI.
Do you have any suggestion on this issue?

Don't have to be rush, answer this when you have time.
Thank you!

**Comment by phann-phearoen** [comment]
I did it!! at last.
I shattered the internet to find the answer.
With Vue I18n, I can easily install Japanese language package from Quasar, and use it.
Then boom, it works like magic!!
Thanks for following up, now you only need to test the output.

**Comment by geonsangyoo** [comment]
@phann-phearoen 

I cannot try to check your work due to serve error during execution of server.
A new issue ( #45 ) is uploaded.

**Comment by geonsangyoo** [comment]
@phann-phearoen 
Confirmed
