### ISSUE TITLE
Mobile Mode width of その他ご質問等 input is smaller than others （予約フォーム）

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#39]
Width of the その他ご質問等 input is smaller than others inputs.
Best to align all the input fields in the entire 予約フォーム to be equal in Mobile Mode.

Code Location: components/YoyakuForm.vue & components/yoyaku-contact-row/ContactRow.vue

**Comment by geonsangyoo** [comment]
@phann-phearoen 
Confirmed
