### ISSUE TITLE
Phone Number Validation is still warning even the right numbers (予約フォーム）

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#40]
Ask Japanese for their phone number format to set the logic.

Code Location: components/YoyakuForm.vue

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Good validations!

One more enhancement on your form!
Could you please add a placeholder on the form (e.g. : 070-1234-5678) ?
It is to induce users to populate the form in a right way (in this case, they have to follow phone rules of Japanese)

![Screen Shot 2021-08-13 at 11 45 21](https://user-images.githubusercontent.com/14138179/129298044-bed5ce06-ec23-4f31-b1f9-95df3c357a13.png)

**Comment by phann-phearoen** [comment]
Sure,
Right away, sir

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Thanks!
Please remind me if you put a placeholder on it and compose a new pull request!

**Comment by phann-phearoen** [comment]
It's done!
Checkout the new branch

**Comment by phann-phearoen** [comment]
However, it feels a bit unusual to have only one place holders in 2 input fields next to each other.
Shall we put place holder in all 3 fields?
Something like this.
![image](https://user-images.githubusercontent.com/74291680/129300250-9b5fa51a-e37b-4bf1-add8-be123f004d67.png)

**Comment by geonsangyoo** [comment]
@phann-phearoen  

It makes sense.

How about each placeholders like below?

お名前を入力してください

電話番号を入力してください ( 例 : 070-1234-5678)

メールアドレスを入力してください

その他ご質問等を入力してください

**Comment by phann-phearoen** [comment]
Ok, right away!
But it feels a bit too long, don't you think?
Like this: 

![image](https://user-images.githubusercontent.com/74291680/129300717-0b02438c-cb04-43ef-b8f8-9d701643d5a9.png)

**Comment by phann-phearoen** [comment]
A lot more problematic in Mobile mode: 

![image](https://user-images.githubusercontent.com/74291680/129300769-1f547286-b394-49a0-a60e-ab46124ae112.png)

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Thank you for your ideas!
umm...I think FB session takes longer and seem to have no limits haha....
it might be better off asking Koda-san to take a review once more based on current status.

I will merge your PR now and upload to server. Thanks.

**Comment by geonsangyoo** [comment]
@phann-phearoen 
Confirmed
