### ISSUE TITLE
EndTime value doesn't show up after input （予約フォーム）

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#41]
EndTime value doesn't show up even after the time has been picked.
Even though I don't experience this problem myself.?

**Comment by phann-phearoen** [comment]
I'm a bit confused with this issue raised by Mr Kodai.
![image](https://user-images.githubusercontent.com/74291680/128831561-1f79b596-9197-4a9c-b12e-4167f960fb91.png)

It seems he mentions that the 'end-time' doesn't display even after he selected.
But when I try it myself, it seems to be working just fine.
![image](https://user-images.githubusercontent.com/74291680/128831519-42452906-dc43-46fb-b9ca-6ee8ecbb68e4.png)

I don't know how to properly respond to this, should I ask him in the chatwork group?

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Hi, Phann!
My apologies to reach out to you too late!

Yes, I confirmed it works well. I am going to ask Kodai-san to check out this issue to be specific.
please hang on a sec.

**Comment by geonsangyoo** [comment]
@phann-phearoen 
Confirmed
