### ISSUE TITLE
There is an error occurred after execution of server

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#45]
@phann-phearoen 

Is there something happened after typing `npm run serve`?

<img width="559" alt="Screen Shot 2021-08-13 at 1 07 38" src="https://user-images.githubusercontent.com/14138179/129230556-1e6a54b4-965c-469a-aeb6-cf891c3f03f9.png">

I cannot check out your works due to the error above.
Do you have any ideas or something you can notice?

Thank you in advance.

**Comment by phann-phearoen** [comment]
Issue has been fixed!

![image](https://user-images.githubusercontent.com/74291680/129293350-9908b9a9-ff71-4b65-9fb4-86bb63368c69.png)

Have a good day bossie!

**Comment by geonsangyoo** [comment]
> Issue has been fixed!
> 
> ![image](https://user-images.githubusercontent.com/74291680/129293350-9908b9a9-ff71-4b65-9fb4-86bb63368c69.png)
> 
> Have a good day bossie!

Good! Good! you already became a master of Vue! haha! Thanks!
