### ISSUE TITLE
No router-links on logo image

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#48]
![Screen Shot 2021-08-13 at 12 38 49](https://user-images.githubusercontent.com/14138179/129301715-5a4d30e7-475f-46d4-a5f2-bb77aeb4990b.png)

Please add router-links (hyper-link) on logo image in order to redirect to main page when user clicked it.

**Comment by phann-phearoen** [comment]
Ahha, I just deleted it thinking it's not necessary.
Put it back now,

**Comment by phann-phearoen** [comment]
It's done!
