### ISSUE TITLE
Set up WG official website's mail service on EmailJs

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#57]
Please link  saiyou@wannagrow.co.jp 
to mail service on EmailJs, and provide me the specifications like serviceID, userID, ect 
since I don't have access to the website I can't set up on my own.

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Hey, Thank you for contact!
Sorry for my replies to be late as it has been long holiday until yesterday in Japan!

I am sure you can check `serviceID `, `userID ` information via below account.

```
login url : https://dashboard.emailjs.com/sign-in
email : date@wannagrow.co.jp
password: qH6xRtgVBw2YrKG
```

Just reck it on!! :)
Please let me know if you have any troubles!  Thx!

**Comment by phann-phearoen** [comment]
How cool!!
I'm happy to hear you have a holiday actually. lol
As you the one who sometimes assigned issues at 1am.
Thanks for the reply, and take care bossy!

**Comment by phann-phearoen** [comment]
Ahh, one change though!
Mr Kodai quoted "そうだね！社内への通知は、date@wannagrow.co.jp　ではなくて、　saiyou@wannagrow.co.jp宛てでよろしく！" in his last feedback.
So the website that we need to link to EmailJs is saiyou@wannagrow.co.jp not date@wannagrow.co.jp.
Please register saiyou@wannagrow.co.jp to EmailJs or clarify the inquiry with Mr Kodai!

**Comment by geonsangyoo** [comment]
@phann-phearoen 

I registered new service linked to `saiyou@wannagrow.co.jp` on same account that I shared.
Please check it out and create a new form for mamasuku!

<img width="775" alt="Screen Shot 2021-08-17 at 13 16 15" src="https://user-images.githubusercontent.com/14138179/129662848-d888fc99-8233-405d-bd8a-5f80d523fe6b.png">

**Comment by phann-phearoen** [comment]
Right away!
