### ISSUE TITLE
Resolving EmailJs Template Limitation

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#58]
EmailJs registered with date@wannagrow.co.jp is now ran out of Template slots.
Please resolve this issue.

**Comment by geonsangyoo** [comment]
@phann-phearoen

Sorry! I didn't realize that!
Please use the account below as a new one is created!

```
id: saiyou+1@wannagrow.co.jp
pw: 9!hYdb.TqZ&$AsT
```

**Comment by phann-phearoen** [comment]
Great!
You’ll have a good news tomorrow then!

2021年8月17日(火) 午後7:02 geonsangyoo ***@***.***>:

**Comment by phann-phearoen** [comment]
Ahaw, service is not created!
I don't have the Host and Port specification of saiyou+1@wannagrow.co.jp

![image](https://user-images.githubusercontent.com/74291680/129819124-989b600f-aaaa-4bf7-99fe-7e70427afb86.png)

Please create it for me.

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Morning!! Oops!!

It is my mistake!!

Please check it once again!! My apologies for inconvenience!

<img width="1026" alt="Screen Shot 2021-08-18 at 11 04 42" src="https://user-images.githubusercontent.com/14138179/129825374-2ca0aa25-7748-4cf2-9d47-50c13ce6812c.png">

**Comment by phann-phearoen** [comment]
Great!

**Comment by phann-phearoen** [comment]
@geonsangyoo 
Mails are all done.
Please test it when you have time!

**Comment by geonsangyoo** [comment]
@phann-phearoen

Hey!
Nice work!! 
All email related forms are working well!! :)

![Screen Shot 2021-08-18 at 18 08 27](https://user-images.githubusercontent.com/14138179/129871329-f85daa98-b8c6-4adc-b56b-47add9e7e9a3.png)
![Screen Shot 2021-08-18 at 18 08 38](https://user-images.githubusercontent.com/14138179/129871336-d5d1f059-8aad-4cfb-8f59-760e63bcb0b7.png)


I guess one light issue is left!!!!
Please refer issue tab! :)

Thank you always! ^ ^
