### ISSUE TITLE
The message after mail sent should be changed to JA

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#60]
Please translate the english message into JA one(`メールを送信しました` ) when the email is sent for all forms.

- [ ] 予約フォーム

![Screen Shot 2021-08-18 at 18 07 24](https://user-images.githubusercontent.com/14138179/129871689-cd575047-67a8-4ce9-8871-b8bd1e90c1d3.png)

- [ ] お問い合わせフォーム

![Screen Shot 2021-08-18 at 18 06 38](https://user-images.githubusercontent.com/14138179/129871686-a8611c89-a236-47c7-b563-291533e88420.png)

**Comment by phann-phearoen** [comment]
Roger sir!

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Plus, `Close` should also be translated into `閉じる`.

If you cannot customize the `Close` button, please search other msg box editable from QUASAR framework.

**Comment by phann-phearoen** [comment]
Great!

**Comment by geonsangyoo** [comment]
@phann-phearoen 

<img width="349" alt="Screen Shot 2021-08-19 at 13 02 50" src="https://user-images.githubusercontent.com/14138179/130005851-c01203c3-954b-467f-a55c-440e1609c4c6.png">

↓

<img width="302" alt="Screen Shot 2021-08-19 at 13 07 28" src="https://user-images.githubusercontent.com/14138179/130006161-b05a651d-07af-4f98-a317-0ffdb0d884a0.png">


Hey, awesome job!

The only one you additionally perform is to remove text(`アラート`) and lessen size of height by half.

**Comment by phann-phearoen** [comment]
On it bossy!

**Comment by phann-phearoen** [comment]
Done

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Confirmed. I will close this issue.
