### ISSUE TITLE
Scrollbehavior requirement imposibility

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#61]
During the last fb from Mr Kodai, there was this comment:
"7 相談する　をタップしたあと、ご予約フォームが見えるところに飛ぶようになっているが、
  スクロールで上にあがって飛ぶのではなく、タップした瞬間にご予約フォームが見えるところに飛ぶようにしてほしい"
I claimed that the issue was solved, but it turns out, it was ok only there was a glitch on my laptop that disrupted the Vue animation.

This is what we have now:

https://user-images.githubusercontent.com/74291680/129873477-4921e0e1-d303-4c43-9ecb-81a2093537ff.mp4

It appears that is the default behavior of Vue Router, which I can't customize. I have done a lot of research about it, but still can't find any working solution.

Do you have any suggestion for this??

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Roger that. 

Please confirm the PR  #62  uploaded.

Thank you in advance.
