### ISSUE TITLE
1 Video cards size modification

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#65]
Change this ratio:
![image](https://user-images.githubusercontent.com/74291680/130029849-4c98bf86-760c-43e2-b52e-e5ad944e93c6.png)

to this ratio:
![image](https://user-images.githubusercontent.com/74291680/130029873-196a6163-627b-4c55-b6a2-8330d10b787e.png)

**Comment by geonsangyoo** [comment]
@phann-phearoen

Confirmed
