### ISSUE TITLE
4 Over offset due to The Top section

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#68]
When clicked on 学べる動画 this shows up:
![image](https://user-images.githubusercontent.com/74291680/130044875-d4f34d4e-473b-485e-b6a8-285006f57a7c.png)

instead of this:
![image](https://user-images.githubusercontent.com/74291680/130044997-1870648d-9ca1-4217-88ab-da4d9b6cd206.png)

**Comment by phann-phearoen** [comment]
@geonsangyoo 
I need your help in this issue too.
This one is a bit hard to achieve as I have spent yesterday's over-time-working  and this entire morning, but still go nowhere.
Please read the description above for contexts.
The issue is that the two elements are wrapped up in the same wrapper.
Hence, when we direct the router to the element, it will be scrolled to this:

![image](https://user-images.githubusercontent.com/74291680/130184773-63de8dac-29fc-46b3-8090-da43d3ee3e73.png)

not the actual section we want it to be:
![image](https://user-images.githubusercontent.com/74291680/130185100-401740b6-7213-4ca5-a7b4-59865138d500.png)


It could be easily solved if we separate them, but we can't because we need them to be inside that same pink border.
I have tried Vue Teleport, Vue-Scrolled to, ect, but non of them works.

Please let me hear your suggestion!!

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Confirmed. Please refer PR I registered ( #76 )

Thanks.
