### ISSUE TITLE
7&8 Move to the top after mail has been sent

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#71]
Apply in both 問い合わせ＆予約フォーム

「7 お問い合わせを送った時の動作について
　送信完了後は、トップページ表示でいいかな。
あと、送信中のときに一旦すべての項目が空欄になるけどこれも変な感じするな」

I partially understand this issue, please kindly explain this!

**Comment by geonsangyoo** [comment]
@phann-phearoen 

This requirement is being confirmed with Kodai-san via Chatwork.
Please check out queries there.

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Please only handle below issue.

```
7 お問い合わせを送った時の動作について
送信完了後は、トップページ表示でいいかな。
```

Thank you in advance.

**Comment by phann-phearoen** [comment]
I already handled the one in お問い合わせ. Please check my PR to see if it is the
desired behavior!
2021年8月20日(金) 午後6:20 geonsangyoo ***@***.***>:

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Confirmed
