### ISSUE TITLE
Go To Douga Title

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#78]
We are not going anywhere with this issue yet.
By removing the **douga** section out of v-scroll-spy, it surely let our **goToDougaTitle** stop corrupting the rest of the functionality.
However, by changing our menu item from: 

`<router-link></router-link`
to:
`<div></div>`

will not provide link to link back when we clicked it from the other page like **予約フォーム** because it has no **to=""** prop.

**Comment by phann-phearoen** [comment]
@geonsangyoo The issue is solved again.

You will not believe what I did. I was so frustrated with the issue, so my solution was to put 2 different methods to the element.
`@mousedown="goToDouga"
 @click="goToDougaTitle"`

**goTouDouga()** I provide the route link
`this.$router.push('/vue-pages/home#douga');`

and **goToDougaTitle()** is just like what you did:
`window.scrollTo({ top: obj.offsetTop - os, behavior: "smooth" });`

**os** is a dynamic value to adjust all offsets accordingly to the screensize.

It is now working!

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Confirmed
