### ISSUE TITLE
favicon is not showing

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#8]
@phann-phearoen 

Please add favicon image file and set it to the page to appear it on the browser.

<img width="338" alt="Screen Shot 2021-07-22 at 0 56 08" src="https://user-images.githubusercontent.com/14138179/126520597-a8328cf8-0836-4d3a-9c1d-bbd3326128ab.png">

**Comment by phann-phearoen** [comment]
I’ll be on it tomorrow!
Thank you!

2021年7月21日(水) 午後10:57 geonsangyoo ***@***.***>:

**Comment by phann-phearoen** [comment]
Hey, are we what icon are we gonna use here? There's no favicon provided in assets folder!

**Comment by geonsangyoo** [comment]
@phann-phearoen 
It can be confirmed. I get it closed.
