### ISSUE TITLE
Fb3 confirmation

### ISSUE THREAD

**Issue by phann-phearoen** [phann-phearoen/mamasuku-repos#82]
Beside the issue of logo moves upward after clicking on the toggler icon, others issues seem to be all solved.
Please test it out.
There's no new PR, I messed up with some confusion of branches, and ended up merged the new branched into main.
So please checkout the main for the latest code.

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Okay. I will check it out.

Thank you for your endeavor!

**Comment by phann-phearoen** [comment]
@geonsangyoo 
My response to Mr Kodai last feedback has been added.
Some specification of the [２　送信完了のポップアップがなくなってる＆送信完了後は、トップページ表示 ] issue is that,
we use EmailJs for free. We have 200 quota for free mail, but during development I have used it all to test the alert dialog. 

![image](https://user-images.githubusercontent.com/74291680/130429643-04d4d907-c5e0-4b80-b8b0-5e6d8ab88393.png)

I don't know what the plan is, whether to upgrade EmailJs, or create another free account, but please handle that one as always.
Thank you

**Comment by geonsangyoo** [comment]
@phann-phearoen 

It has been resolved. You can check it out in the same account.
