### ISSUE TITLE
input forms enhancement

### ISSUE THREAD

**Issue by geonsangyoo** [phann-phearoen/mamasuku-repos#9]
@phann-phearoen 

<img width="799" alt="Screen Shot 2021-07-22 at 1 02 07" src="https://user-images.githubusercontent.com/14138179/126521623-c5cabbc0-67bd-41ae-8f71-e26fec15d782.png">

<img width="954" alt="Screen Shot 2021-07-22 at 1 02 25" src="https://user-images.githubusercontent.com/14138179/126521628-6ccd3e9e-0a48-4821-9fb7-ed74ef96c376.png">

I thought the input forms you added seem like too out-fashioned.

Please enhance the input UI forms by using `QUASAR framework` on the corresponding page stated below.
It would be better for implementation of trendy UX. 

please consider the link. [(https://quasar.dev/vue-components/input)](https://quasar.dev/vue-components/input)

**Comment by phann-phearoen** [comment]
The framework that I used was better, but I modified it to look like the
requirement. I’ll be on it tomorrow!

2021年7月21日(水) 午後11:04 geonsangyoo ***@***.***>:

**Comment by phann-phearoen** [comment]
which part look outdated the most, do you think?
the entire form including the labels at the left, or just the input fields?
I was only trying to make it look as close as in the requirement as possible, so I need more specific instruction to make it right. for now, I'll try changing the fields by using Quasar elements, but it won't change that much.

**Comment by phann-phearoen** [comment]
![image](https://user-images.githubusercontent.com/74291680/126733419-cf65ac37-6769-4ec4-b62b-c9ed5ad3ff7d.png)
In term of look, do you think this thin border look better? 
How do you think about the height?
Should it be a little larger?

**Comment by geonsangyoo** [comment]
> which part look outdated the most, do you think?
> the entire form including the labels at the left, or just the input fields?
> I was only trying to make it look as close as in the requirement as possible, so I need more specific instruction to make it right. for now, I'll try changing the fields by using Quasar elements, but it won't change that much.

@phann-phearoen

> which part look outdated the most, do you think?

GY : The input forms are only the thing seemed outdated.

> the entire form including the labels at the left, or just the input fields?

GY : I meant only the input fields are the places where to be trendy.

> I was only trying to make it look as close as in the requirement as possible, so I need more specific instruction to make it right. for now, I'll try changing the fields by using Quasar elements, but it won't change that much.

GY : I can totally understand what you are saying. Needless to say, I admit you have been developing the pages under the design file. The point is the functionality & input formats that respond to User's behavior. 

The design file provided by designer you are looking the instructions is just reference in terms of overall layout and UI, no any further instruction about UX(User Experience) is indicated and hard to figure out how to react circumstances from users.

That is why I gave you further feedbacks when it comes to UX perspectives. I hope you can understand that our project is based on Agile methodology (https://www.nvisia.com/insights/agile-methodology).

I mean we are working on recursive flows that are performed that contain the prototype development roughly under the minimum resources, improvement caused by feedbacks to whom it may concern.

Just so you know, I think you are showing us awesome jobs every day! 
No worries although you are easy to feel that I want you to perform further tasks as you seem not following instructions :)

Thank you !

**Comment by phann-phearoen** [comment]
Got it. I kinda take it this way all along. Regarding what you stated, I'll tweak whatever I can and give you more result soon.

**Comment by geonsangyoo** [comment]
@phann-phearoen 

Thank you :)
please let me know when you cover all you can handle.

Let's talk about #12 issue together via ZOOM!

**Comment by phann-phearoen** [comment]
Yeah, please set the time

**Comment by geonsangyoo** [comment]
@phann-phearoen 

> Yeah, please set the time

Sure. I will share it to you next week! 
Please let me know once you have done the rest of the issues!

**Comment by geonsangyoo** [comment]
@phann-phearoen 
It can be confirmed. I get it closed.
